In [1]:
import numpy as np
import pandas as pd

df = pd.read_csv("종관기상관측(2019)_0119.csv",encoding = 
                 'euc-kr',index_col = 0)

In [2]:
df["일강수량(mm)"].fillna(0,inplace =True)

In [3]:
df=df.dropna(axis = 0 )

In [4]:
df.head()

지점명          일시  평균기온(°C)  최저기온(°C)  최고기온(°C)  일강수량(mm)  최대 순간 풍속(m/s)  \
지점                                                                           
184  제주  2019-01-01       5.6       4.8       7.0       0.0           13.6   
184  제주  2019-01-02       5.1       4.5       6.1       0.0           11.4   
184  제주  2019-01-03       5.1       3.5       8.0       0.0            8.2   
184  제주  2019-01-04       5.8       2.6      10.0       1.6            7.6   
184  제주  2019-01-05       7.0       5.2       9.0       0.0            8.9   

     최대 순간 풍속 풍향(16방위)  최대 풍속(m/s)  최대 풍속 풍향(16방위)  ...  평균 현지기압(hPa)  \
지점                                                  ...                 
184              320.0         7.6           320.0  ...        1031.7   
184               22.5         6.2           360.0  ...        1031.7   
184               14.1         5.1            20.0  ...        1031.8   
184               30.9         4.6            20.0  ...        1027.2   
184                0.0         5.1           360.0  ...        1023.5   

     최고 해면기압(hPa)  최저 해면기압(hPa)  평균 해면기압(hPa)  가조시간(hr)  평균 전운량(1/10)  \
지점                                                                      
184        1035.5        1032.3        1034.3      10.0           9.0   
184        1035.9        1032.2        1034.3       9.9           8.8   
184        1036.6        1033.2        1034.4       9.9           4.1   
184        1033.7        1027.2        1029.8       9.9           8.1   
184        1027.5        1024.6        1026.0       9.9           5.9   

     평균 중하층운량(1/10)  평균 지면온도(°C)  최저 초상온도(°C)    분류  
지점                                                   
184             9.0          4.8          4.3  45.0  
184             8.8          4.6          2.9  45.0  
184             4.1          5.5         -1.8  54.0  
184             6.3          5.2         -2.6  41.0  
184             5.1          6.6          0.1  52.0  

[5 rows x 27 columns]

In [5]:
X, y = df.iloc[:,2:-1],df.iloc[:,-1]

In [6]:
X.shape

(364, 24)

In [7]:
x_cen = X - X.mean(axis = 0)
x_cov = np.dot(x_cen.T , x_cen) / 363
print(x_cov)

[[ 5.34302197e+01  5.36865749e+01  5.41279565e+01  2.98501190e+01
  -3.16259861e+00 -1.16143697e+02 -1.00328974e+00 -4.12284042e+02
  -1.73895090e+00 -1.50905235e+05 -3.79168634e+02  6.09713096e+01
   4.26435336e+01  4.87711355e+01  5.70569575e+01 -4.79991579e+01
  -5.02190962e+01 -6.38545335e+01 -4.85485213e+01  9.44472520e+00
  -7.19007129e-01 -3.47088116e+00  5.79104894e+01  5.65973908e+01]
 [ 5.36865749e+01  5.53277026e+01  5.35092641e+01  3.25789886e+01
  -3.04348197e+00 -1.19771693e+02 -9.49005540e-01 -4.07075561e+02
  -1.50060334e+00 -1.32378829e+05 -3.67746163e+02  6.27471307e+01
   5.07979869e+01  5.48398226e+01  5.92354757e+01 -4.88857691e+01
  -5.13971138e+01 -6.38205752e+01 -4.94336361e+01  9.59149669e+00
   4.96929737e-01 -2.19962765e+00  5.82541740e+01  5.94517946e+01]
 [ 5.41279565e+01  5.35092641e+01  5.62654772e+01  2.66617719e+01
  -2.98186541e+00 -9.92937820e+01 -8.55029516e-01 -4.13350157e+02
  -1.80738489e+00 -1.53647892e+05 -3.83796734e+02  6.07567218e+01
   3.696

In [8]:
# 고유값 분해
w ,v =np.linalg.eig(x_cov)
print(w)
print("----------------",v)

[8.97614633e+09 3.17701372e+04 9.00997272e+03 5.64646650e+03
 3.77569688e+03 7.09809044e+02 3.06831188e+02 1.95373927e+02
 3.94222007e+01 1.53421670e+01 8.49057026e+00 7.22797744e+00
 3.18110486e+00 2.84597266e+00 1.61569168e+00 8.43883236e-01
 6.91844395e-01 6.34636073e-01 6.09932985e-04 2.87185990e-01
 2.47029929e-01 2.13331062e-01 9.24984463e-02 9.89827104e-02]
---------------- [[ 1.68118373e-05  1.48709165e-02  2.03468170e-02 -1.47101440e-02
   2.99144745e-03 -1.69256563e-01 -1.65100347e-01  2.00783032e-01
   2.16935167e-01  6.32427594e-03 -5.09999858e-02  9.51700440e-02
   2.23915330e-01 -1.81976152e-01  8.67652934e-02  3.48501290e-02
  -1.62525853e-01  1.08513196e-01 -8.09936613e-03 -7.40841108e-02
   8.28972282e-02  7.49130008e-02  5.62356107e-01  6.16191796e-01]
 [ 1.47478771e-05  1.49476236e-02  1.94810808e-02 -1.44230231e-02
   3.66785058e-03 -1.84095914e-01 -1.70220149e-01  1.72824097e-01
   2.33957745e-01 -4.72636504e-02 -8.50654129e-02 -1.02710057e-01
   1.66039316e-02 -1.

In [12]:
from sklearn.decomposition import PCA

pca = PCA(n_components=3)
pca.fit(X)
PCA(copy=True, iterated_power='auto', n_components=3, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)
print('singular value :', pca.singular_values_)
print('singular vector :\n', pca.components_.T)


singular value : [1805087.56559844    3395.9622783     1808.48558158]
singular vector :
 [[-1.68118373e-05  1.48709165e-02 -2.03468170e-02]
 [-1.47478771e-05  1.49476236e-02 -1.94810808e-02]
 [-1.71173865e-05  1.46436870e-02 -2.21931780e-02]
 [ 4.27177775e-05  1.96401495e-02 -1.14369227e-02]
 [ 3.27447387e-05  1.78103884e-03 -1.28530126e-03]
 [ 2.16388016e-04 -5.15001791e-01 -8.30119732e-01]
 [ 1.61690639e-05  1.53163518e-03 -9.22637672e-04]
 [ 3.21331977e-04 -6.68741047e-01  2.70816380e-01]
 [ 1.05435848e-05 -2.90252878e-04  6.05223724e-05]
 [ 9.99999860e-01  5.15640657e-04 -7.47601262e-05]
 [ 3.53783690e-04 -5.31788136e-01  4.62009454e-01]
 [-1.85011017e-05  1.98976940e-02 -2.22031025e-02]
 [-3.40515121e-06  2.14657553e-02 -1.82914341e-02]
 [-8.71972552e-06  2.55136322e-02 -1.61650960e-02]
 [-1.58371503e-05  1.75089020e-02 -1.98845164e-02]
 [ 3.58972860e-06 -1.48766868e-02  1.93483761e-02]
 [ 9.14281529e-06 -1.50501526e-02  1.92750599e-02]
 [-1.13953626e-05 -2.60036881e-02 -1.3844881

In [14]:
pca.singular_values_

array([1805087.56559844,    3395.9622783 ,    1808.48558158])

In [16]:
print('eigen_value :', pca.explained_variance_)
print('explained variance ratio :', pca.explained_variance_ratio_)


eigen_value : [8.97614633e+09 3.17701372e+04 9.00997272e+03]
explained variance ratio : [9.99994263e-01 3.53937578e-06 1.00376272e-06]


In [17]:
# PC1에 projection
pc1 = v[:, 0]
proj1 = np.dot(X, pc1)

# PC2에 projection
pc2 = v[:, 1]
proj2 = np.dot(X, pc2)

# PC3에 projection
pc3 = v[:, 2]
proj3 = np.dot(X, pc3)

proj_list = np.array([proj1.var(), proj2.var(), proj3.var()])

print('variance(==eigenvalue) :', proj_list)
print('explained variance ratio :', proj_list / proj_list.sum())



variance(==eigenvalue) : [8.95148659e+09 3.16828566e+04 8.98522005e+03]
explained variance ratio : [9.99995457e-01 3.53938000e-06 1.00376392e-06]


In [20]:
cumsum = np.cumsum(pca.explained_variance_ratio_)
d = np.argmax(cumsum >= 0.95) + 1
print('선택할 차원 수 :', d)


선택할 차원 수 : 1


In [22]:
pca = PCA(n_components=0.95)
X_proj = pca.fit_transform(X)
print('principal component vec :\n', pca.components_.T)

#https://excelsior-cjh.tistory.com/167

principal component vec :
 [[-1.68118373e-05]
 [-1.47478771e-05]
 [-1.71173865e-05]
 [ 4.27177775e-05]
 [ 3.27447387e-05]
 [ 2.16388016e-04]
 [ 1.61690639e-05]
 [ 3.21331977e-04]
 [ 1.05435848e-05]
 [ 9.99999860e-01]
 [ 3.53783690e-04]
 [-1.85011017e-05]
 [-3.40515121e-06]
 [-8.71972552e-06]
 [-1.58371503e-05]
 [ 3.58972860e-06]
 [ 9.14281529e-06]
 [-1.13953626e-05]
 [ 3.71466112e-06]
 [-2.93015352e-06]
 [ 5.82670610e-06]
 [ 9.14089355e-06]
 [-2.05412144e-05]
 [-8.46428286e-06]]
